{
 "title": "Webinar \"Privacy with Loki\" - PII Audit dashboard",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n       <img src=\"https://drive.google.com/uc?export=view&id=1OpV69Pm0pN4OjkuI6xp3erQ4cZ8Qrvh0\" width=\"300px\">\n     </td>\n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-family: Verdana;font-size: 40px;color: #FB755A\">PII Audit dashboard</h1>\n<br \\>\nThis dashboard is part of a demo specifically built for the webinar \"<a href=\"https://grafana.com/go/webinar/apac-managing-log-privacy-with-loki/\" target=\"_blank\">Managing privacy in log data with Grafana Loki</a>\".\nThe objective is to illustrate how the Grafana Agent and Loki can help to integrate policy rules for log data.\n<br \\><br \\>\nYou can visualise in this dashboards the PII captured by the <a href=\"https://grafana.com/docs/agent/latest/\" target=\"_blank\">Grafana Agent</a>/<a href=\"https://grafana.com/docs/loki/latest/clients/promtail/\" target=\"_blank\">Promtail</a>.\n<br \\><br \\>\nThese PII are captured and obfuscated by the Grafana Agent/Promtail using <a href=\"https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/\" target=\"_blank\">\"replace\" stage</a>.\n<br \\><br \\>\nThese PII are exposed as Prometheus metrics using the Grafana Agent/Promtail <a href=\"https://grafana.com/docs/loki/latest/clients/promtail/stages/metrics/\" target=\"_blank\">\"metrics\" stage</a>."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total PII captured",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(promtail_custom_sensitive_data_email_total[$__range])) + floor(increase(promtail_custom_sensitive_data_cc_number_total[$__range]))"
    }
   ]
  },
  {
   "title": "Total \"Emails\" captured",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(promtail_custom_sensitive_data_email_total[$__range]))"
    }
   ]
  },
  {
   "title": "\"Contact form\" log stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"webinar\"}"
    }
   ]
  },
  {
   "title": "Total \"Credit card numbers\" captured",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(promtail_custom_sensitive_data_cc_number_total[$__range]))"
    }
   ]
  },
  {
   "title": "Rate - PII intercepted",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(promtail_custom_sensitive_data_email_total[10m])",
     "legendFormat": "Emails detected"
    },
    {
     "expr": "rate(promtail_custom_sensitive_data_cc_number_total[10m])",
     "legendFormat": "CC # detected"
    }
   ]
  }
 ]
}